// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0sCeLAwLTKE-1bNfg04REbTpqmDXsMNs',
    appId: '1:393930989494:web:c42ce3d583c1e16e21ab17',
    messagingSenderId: '393930989494',
    projectId: 'proyecto2-d1955',
    authDomain: 'proyecto2-d1955.firebaseapp.com',
    storageBucket: 'proyecto2-d1955.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBioGsjF-2-KY45T_BJGAvydzLugsbCdOc',
    appId: '1:393930989494:android:1381bb55ec2034e421ab17',
    messagingSenderId: '393930989494',
    projectId: 'proyecto2-d1955',
    storageBucket: 'proyecto2-d1955.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8n51H6Ekjwv7Yur5Z0X_-f26HKFoylGE',
    appId: '1:393930989494:ios:a589400fc5da690121ab17',
    messagingSenderId: '393930989494',
    projectId: 'proyecto2-d1955',
    storageBucket: 'proyecto2-d1955.appspot.com',
    iosClientId: '393930989494-dpj1t8bg57bh0h9dmf8j5hbic9k4169l.apps.googleusercontent.com',
    iosBundleId: 'mx.edu.ittepic.damU4Proyecto217401034',
  );
}
